// genetal
export const ERROR = "ERROR";

// project
export const GET_PROJECTS_SUCCESS = "GET_PROJECTS_SUCCESS";
export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS";
export const DELETE_PROJECT_SUCCESS = "DELETE_PROJECT_SUCCESS";
export const UPDATE_PROJECT_SUCCESS = "UPDATE_PROJECT_SUCCESS";
export const SET_CURRENT_PROJECT_ID = "SET_CURRENT_PROJECT_ID";
export const GET_CURRENT_SUCCESS = "GET_CURRENT_SUCCESS";
export const CLEAR_CURRENT_PROJECT = "CLEAR_CURRENT_PROJECT";
export const SET_DELETED = "SET_DELETED";
export const CLOSE_MODAL = "CLOSE_MODAL";
export const GET_CLIENTS_SUCCESS = "GET_CLIENTS_SUCCESS";
export const CLEAR_PROJECT_DATA = "CLEAR_PROJECT_DATA";

// alert
export const SHOW_ALERT = "SHOW_ALERT";
export const HIDE_ALERT = "HIDE_ALERT";

// auth
export const REGISTER = "REGISTER";
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const GET_USER = "GET_USER";
export const SET_LOADING = "SET_LOADING";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const HIDE_AUTH_ERROR = "HIDE_AUTH_ERROR";
export const HIDE_LOGIN_ERROR = "HIDE_LOGIN_ERROR";
